### ISSUE TITLE
[Feature] Monitor 2 ISP (Starlink and Local Telco)

### ISSUE THREAD

**Issue by chivarpilones** [gnmyt/MySpeed#525]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Hello guys, I would like to know how to "add" another gateway to monitor bandwidth 

My Hardware is Raspberry Pi 5 
Eth0 = 192.168.1x
Wlan0 = 192.168.254.x

is there a way to monitor these two at the same time? and instead of continuously checking can it be 5 minutes instead?

**Comment by fynnsh** [comment]
just make two docker containers for both networks..

**Comment by gnmyt** [comment]
Hi. Like @fynnsh already said, if you are using Docker, the easiest way would be to create two Docker containers and give them access to the different network interfaces.
However, I will implement a way to change the network interface directly on the server side as I think this is important for ease of use.

For your second suggestion: If you don't want to use the default 1 hour / 1 minute checks you can write your own crown extension on when to run tests. In your case, go to `Set freuqency` > `Set manually` > `*/5 * * * *` > `Update`

**Comment by kennyrkun** [comment]
I was going to suggest a feature like this, but I'm glad to see it's at least possible with the current setup. I think it would be beneficial to run both tests from a single instance of the container, and view them in the same interface. It is more efficient and easier to compare in the same interface rather than switching between two entirely separate instances of the application. Is this a lot of work?
