### ISSUE TITLE
[Feature] my feature idea after using the project... (be able to modify the notification / webhook from the ui) and also (pause test ...)

### ISSUE THREAD

**Issue by torik988** [gnmyt/MySpeed#526]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

For the message part, be able to modify the content of the message (for example, via Discord to customize it, add other 
    information, variables, pictures with a small report, etc.). A small JPG with stats could also be included.

    I don't know if this already exists, but if the speed drops below a certain amount for too long, send a notification.

For the pause part, add a feature on the main page where we can add other servers.
    Include a feature to pause the server directly without having to open its dashboard. Also, add a rust color around it, just like it is 
    currently. I don't know if this is really clear, but if it's not, I can provide more details.

**Comment by gnmyt** [comment]
Hey, sorry for the delay. 

For the discord part, you can already set custom messages in the dialog. You can also add a profile picture directly in the Discord webhook settings, but anything beyond that (embeds, attachments) would make the integration menu too bloated and complicated. If you want to implement your own custom logic on what should happen with the data, you would need to create a new webhook and implement the logic on your own.

I'm not sure if I understood your second part correctly, but if you are talking about adding new servers, you can already do that in the menu on the top left. However, you still need to pause them individually by clicking on them since it would cost too many resources if I also asked the pause state of every server in the list every few seconds.

I'm closing this issue for now, but feel free to submit other ideas or re-open this issue if I understood something wrong.
