### ISSUE TITLE
[Bug] Restarting the Docker Engine triggers a new speedtest run

### ISSUE THREAD

**Issue by scara** [gnmyt/MySpeed#547]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

Hi,
I've just updated my OS: among the packages even `containerd.io docker-ce docker-ce-cli docker-ce-rootless-extras docker-compose-plugin` i.e. `docker` has been restarted including `germannewsmaker/myspeed:1.0.8`.
Going back to MySpeed I'd a brand new speedtest run at the time of the restart, without any relation with the schedule manually set in MySpeed since the installation of the image (6h).

Thanks in advance,
Matteo

### What device are you using to access the page?

In the browser

### Which operating system is your MySpeed instance running on?

Linux

**Comment by gnmyt** [comment]
Hey, that was actually by design. In the first versions, MySpeed didn't have a UI that would show if no tests are in the database, and it only stored tests up to 24 hours, so it would create one on start to be sure it gets displayed correctly.

However, this is no longer the case. The code for this behaviour hasn't changed though.

I get that this is confusing so I'm gonna remove this and put it behind an environment variable in case someone still wants this behaviour. Thanks for pointing this out!
