### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AlexCromer** [gnmyt/MySpeed#606]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

Manual tests consistently show my true speeds from my ISP, however every single one of the automated tests show results that are about 300Mbps lower on uploads and about 400Mbps lower on downloads...Is there a configuration I'm not considering/aware of?

Currently running the service as a docker container on my hard-lined Synology NAS

### What device are you using to access the page?

In the browser

### Which operating system is your MySpeed instance running on?

Linux

**Comment by gnmyt** [comment]
That's actually not the first time this issue has been reported (#531). I might get back to you for testing since I couldn't reproduce this issue on my own. My hope is that this issue gets resolved when I implement the "Multiple Providers" update.

Thank for submitting that though, I'm going to take a deeper look into that.
