### ISSUE TITLE
[Feature] Login page

### ISSUE THREAD

**Issue by martinjgrunwald** [gnmyt/MySpeed#716]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Maybe you could add a user management with a login page

**Comment by gnmyt** [comment]
Hi, thanks for your suggestion. In general, I like the idea of a user management system, as you can assign different permissions to different users. However, in this case I wanted to make MySpeed as simple as possible, and since the settings you can change are already limited to the administrator, I don't think it would add much here.

If you want others to see your test data but not change your settings, you can set a password level (`Settings` > `Change password` > `Change level` > `Read-only Access`). When applied, anyone who has access to this page can see your results but cannot change anything.

I'm closing this issue for now, but if you have any questions about it, feel free to reopen this issue or if you have another idea, create a new issue :)
