### ISSUE TITLE
[Feature] Allow api access to trigger speed tests

### ISSUE THREAD

**Issue by twistedsanity** [gnmyt/MySpeed#722]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

My plan would be to disable scheduled speed tests as they can often conflict with high traffic times, and use external monitoring to trigger a test. E.g. I monitor the external interface flow at my firewall and once it drops beneath a set level for more than 'x' seconds trigger a speed test (limited to 1 per hour) 

To allow for this I need to be able to disable all speed test schedules, and allow the tests to be triggered remotely. Also if possible I would like the results/stats to be also available via an api to allow for my home automation system to query and display results on screens around the house when needed.

**Comment by gnmyt** [comment]
Hi, thanks for your suggestion. MySpeed already has a simple REST-API you can hook into. You can find a complete collection of API endpoints [here on Postman](https://documenter.getpostman.com/view/13582348/2sA3XWdKLo).

In order to do what you described, you need to do the following:
1. Disable speedtests. You can do this by setting the crontab (`Settings` > `Set frequency` > `Set manually`) to a time that never executes or takes a really long time (e.g. `0 0 1 1 *` - once a year)
2. Trigger a `POST` request to `/api/speedtests/run`. This is also documented [here](https://documenter.getpostman.com/view/13582348/2sA3XWdKLo#b603a71c-5d2f-4398-8ced-a767d7cf9382)

I'm not sure what home automation system you are using but if it can integrate with Prometheus, you can use the [Prometheus endpoint](https://documenter.getpostman.com/view/13582348/2sA3XWdKLo#31864321-01f8-443f-9795-a1efbe04e1aa) (see #687).

If not, you can get the speedtest data as JSON. You can either get it [raw in a list](https://documenter.getpostman.com/view/13582348/2sA3XWdKLo#4cdb96bd-6bde-4b4e-8288-4c5d60df9b5b), [by averages](https://documenter.getpostman.com/view/13582348/2sA3XWdKLo#ce773538-e3e8-4891-bfb8-c173df116908) or get [the statistics](https://documenter.getpostman.com/view/13582348/2sA3XWdKLo#a5c2b50a-6b45-4169-a273-130ffcccc396). This returns the same data as seen in the UI.

Hope that helps! :)

**Comment by twistedsanity** [comment]
That really does help, I'm just sorry I didn't find this myself. I'm away at the moment but will try this as soon as I return.

I use 'home assistant' so shouldn't have tookmany issues capturing what I need via either method.

Thanks again for the info and pointers.

**Comment by twistedsanity** [comment]
Using home assistant I set up the following in yaml and call the service in an automation.

`rest_command:
  run_speed_test:
    method: post
    url: "http://host:port/api/speedtests/run"`


I am working on pulling results into a dashboard, but that is a lower priority for me. 

Many thanks for your help.
