### ISSUE TITLE
[Feature] Switch Views With a Single Button

### ISSUE THREAD

**Issue by Jaxel** [gnmyt/MySpeed#754]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Right now, to switch the view, you need to press FOUR buttons:

* Settings Icon
* Switch View
* Select the View
* Update

I would like to be able to switch the view with a single button. Perhaps put an icon right next to the [Start Speedtest] [Settings] icons?

**Comment by gnmyt** [comment]
Funny that you mention it, I actually had the same idea a few days ago. I've opened a discussion here: #744.
If you don't mind, please read the discussion there and let me know if you have any changes or like/dislike the changes.

I'm closing this issue for now. If you have any suggestions related to this issue, feel free to answer the discussion or re-open this issue here. Thanks! :)
